USE WAREHOUSE COMPUTE_WH;

USE DATABASE SNOWFLAKE_LEARNING_DB;

CREATE SCHEMA IF NOT EXISTS SILVER;

CREATE OR REPLACE TABLE SILVER.STORE_SALES_CLEAN AS
SELECT 
    SS.SS_SOLD_DATE_SK,
    SS.SS_STORE_SK,
    SS.SS_CUSTOMER_SK,
    SS.SS_QUANTITY,
    SS.SS_SALES_PRICE
FROM BRONZE.STORE_SALES_RAW SS
JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.DATE_DIM D
    ON SS.SS_SOLD_DATE_SK = D.D_DATE_SK
WHERE
    SS.SS_SALES_PRICE IS NOT NULL
    AND SS_QUANTITY > 0;

DESC TABLE SILVER.STORE_SALES_CLEAN;

SELECT
    MIN(SS_SALES_PRICE) AS MIN_SALES_PRICE,
    MAX(SS_SALES_PRICE) AS MAX_SALES_PRICE,
FROM SILVER.STORE_SALES_CLEAN;


select count(*)
from SILVER.STORE_SALES_CLEAN
WHERE SS_SALES_PRICE IS NULL;

SELECT COUNT(*)
FROM SILVER.STORE_SALES_CLEAN
WHERE SS_QUANTITY <=0;

drop table if exists silver