
USE WAREHOUSE COMPUTE_WH;

USE DATABASE SNOWFLAKE_LEARNING_DB;

CREATE SCHEMA GOLD;

create or replace table GOLD.MONTHLY_SALES AS 
SELECT
         DATE_TRUNC('MONTH',transaction_date) AS sales_month,
         SUM(SALES_PRICE) AS TOTAL_SALES 
         FROM SILVER.FACT_SALES 
         GROUP BY SALES_MONTH;


